---
# Install HttpFS
- name: Install mapr-httpfs
  yum: name=mapr-httpfs state=present
  when: ansible_os_family == 'RedHat'
- name: Set owner mapr-system user
  file: path=/opt/mapr/httpfs owner={{ mapr_user }} group={{ mapr_group }} state=directory recurse=yes