---
# Redhat / CentOS
- name: Install MySQL-python (Redhat / CentOS)
  yum: name={{ item }} state=present update_cache=yes
  with_items:
#  - mariadb
  - MySQL-python
  when: ansible_os_family == 'RedHat'
# Debian / Ubuntu
- name: Install python-mysqldb (Debian / Ubuntu)
  apt: name={{ item }} state=present update_cache=yes
  with_items:
#  - mysql-client
  - python-mysqldb
  when: ansible_os_family == 'Debian'
# Suse
- name: Install python-mysql (Suse)
  zypper: name={{ item }} state=present
  with_items:
#  - mariadb-client
  - python-mysql
  when: ansible_os_family == 'Suse'