---
# Redhat / CentOS
- name: Install Midnight Commander (Redhat / CentOS)
  yum: name=mc state=present update_cache=yes
  when: ansible_os_family == 'RedHat'
- name: Install wget (Redhat / CentOS)
  yum: name=wget state=present update_cache=yes
  when: ansible_os_family == 'RedHat'
- name: Install MySQL-python (Redhat / CentOS)
  yum: name={{ item }} state=present update_cache=yes
  with_items:
#  - mariadb
  - MySQL-python
  when: ansible_os_family == 'RedHat'
# Debian / Ubuntu
- name: Install Midnight Commander (Debian / Ubuntu)
  apt: name=mc state=present update_cache=yes
  when: ansible_os_family == 'Debian'
- name: Install wget (Debian / Ubuntu)
  apt: name=wget state=present update_cache=yes
  when: ansible_os_family == 'Debian'
- name: Install python-mysqldb (Debian / Ubuntu)
  apt: name={{ item }} state=present update_cache=yes
  with_items:
#  - mysql-client
  - python-mysqldb
  when: ansible_os_family == 'Debian'
# Suse
- name: Install Midnight Commander (Suse)
  zypper: name=mc state=present
  when: ansible_os_family == 'Suse'
- name: Install wget  (Suse)
  zypper: name=wget state=present
  when: ansible_os_family == 'Suse'
- name: Install python-mysql (Suse)
  zypper: name={{ item }} state=present
  with_items:
#  - mariadb-client
  - python-mysql
  when: ansible_os_family == 'Suse'