- name: Setup global vars
  hosts: all
  roles:
    - mapr-configure-vars
- name: Configure and start
  hosts: mapr-core
  roles:
   - {role: mapr-configure-unsecure, when: mapr_security == 'none'}
- name: Configure and start
  hosts: mapr-core
  roles:
   - {role: mapr-configure-nativesecurity-secure, when: mapr_security == 'native'}
- name: Restarting mapr-zookeeper
  hosts: mapr-zookeeper
  roles:
   - mapr-configure-zookeeper-restart
- name: Restarting mapr-warden
  hosts: mapr-core
  roles:
   - mapr-configure-warden-restart