- name: Apply common configuration to all nodes
  hosts: base
  roles:
    - common-oracle-jdk
    - common-mapruser
    - common-rpcbind
    - common-ntp
    - common-misc
- name: Install MapR Core
  hosts: base
  roles:
    - mapr-configure-repository
    - mapr-core
- name: Install Zookeeper
  hosts: mapr-zookeeper
  roles:
    - mapr-zookeeper
- name: Install CLDB
  hosts: mapr-cldb
  roles:
    - mapr-cldb
- name: Install Gateway
  hosts: mapr-gateway
  roles:
    - mapr-gateway
- name: Install Filesystem, MapReduce2, YARN Node Manager
  hosts: mapr-datanode
  roles:
    - mapr-fileserver
    - mapr-mapreduce2
    - mapr-nodemanager
- name: Install YARN Resource Manager
  hosts: mapr-resourcemanager
  roles:
    - mapr-resourcemanager
- name: Install MySQL
  hosts: ext-mysql
  roles:
    - ext-mysql
- name: Install Drill
  hosts: mapr-drill
  roles:
    - mapr-drill
- name: Install Flume
  hosts: mapr-flume
  roles:
    - mapr-flume
- name: Install HBase CLI
  hosts: mapr-hbase-cli
  roles:
    - mapr-hbase-cli
- name: Install HBase REST and Thrift Server
  hosts: mapr-hbase-thrift-rest
  roles:
    - mapr-hbase-thrift-rest
- name: Install History Server
  hosts: mapr-historyserver
  roles:
    - mapr-historyserver
- name: Install Hive CLI
  hosts: mapr-hive-cli
  roles:
    - mapr-hive-cli
- name: Install Hive MetaStore
  hosts: mapr-hive-metastore
  roles:
    - mapr-hive-metastore
- name: Install Hive Server 2
  hosts: mapr-hive-server2
  roles:
    - mapr-hive-server2
- name: Install Hive WebHCat
  hosts: mapr-hive-webhcat
  roles:
    - mapr-hive-webhcat
- name: Install Mahout
  hosts: mapr-mahout
  roles:
    - mapr-mahout
- name: Install MCS
  hosts: mapr-mcs
  roles:
    - mapr-mcs
- name: Install Pig
  hosts: mapr-pig
  roles:
    - mapr-pig
- name: Install Sqoop 2 Server
  hosts: mapr-sqoop2-server
  roles:
    - mapr-sqoop2-server
- name: Install Sqoop 2 Client
  hosts: mapr-sqoop2-client
  roles:
    - mapr-sqoop2-client
#- name: Install Hue
#  hosts: mapr-hue
#  roles:
#    - mapr-hue
- name: Install Oozie
  hosts: mapr-oozie
  roles:
    - mapr-oozie
- name: Install HttpFS
  hosts: mapr-httpfs
  roles:
    - mapr-httpfs
- name: Install NFS
  hosts: mapr-nfs
  roles:
    - mapr-nfs
- name: Setup global vars
  hosts: all
  roles:
    - mapr-configure-vars
- name: Configure and start
  hosts: base
  roles:
    - mapr-configure-unsecure
- name: Restarting mapr-zookeeper
  hosts: mapr-zookeeper
  roles:
  - mapr-configure-zookeeper-restart
- name: Restarting mapr-warden
  hosts: base
  roles:
  - mapr-configure-warden-restart
- name: Install Spark on YARN
  hosts: mapr-spark-yarn
  roles:
    - mapr-spark-yarn
- name: Install Spark History Server
  hosts: mapr-spark-historyserver
  roles:
    - mapr-spark-historyserver
- name: Restarting mapr-warden
  hosts: base
  roles:
    - mapr-configure-warden-restart
- name: Install Zeppelin
  hosts: ext-zeppelin
  roles:
    - ext-zeppelin
- name: Install MapR client
  hosts: mapr-client
  roles:
    - common-oracle-jdk
    - common-mapruser
    - common-rpcbind
    - common-ntp
    - common-misc
    - mapr-configure-repository
    - mapr-client
    - mapr-nfsloopback

- name: Install R Lang
  hosts: ext-rlang
  roles:
    - ext-rlang

- name: Install R Studio Server Pro
  hosts: ext-rstudioserverpro
  roles:
    - ext-rstudioserverpro