- name: Apply common configuration to all nodes
  hosts: all
  remote_user: ec2-user
  become: yes
  become_method: sudo
  roles:
    - java
    - mapruser
    - rpcbind
    - ntp
- name: Start setup
  hosts: master
  remote_user: ec2-user
  become: yes
  become_method: sudo
  roles:
    - init-setup