- name: Apply common configuration to all nodes
  hosts: all
  roles:
    - java
    - mapruser
    - rpcbind
    - ntp
- name: Start setup
  hosts: master
  become: yes
  become_method: sudo
  roles:
    - init-ui-setup