---
# Install MapR Core components for all machines

# Redhat / CentOS
- name: Install mapr-core
  yum: name={{ item }} state=present
  with_items:
  - mapr-core
  - mapr-core-internal
  when: ansible_os_family == 'RedHat'
# Debian / Ubuntu
- name: Install mapr-core
  apt: name={{ item }} state=present
  with_items:
  - mapr-core
  - mapr-core-internal
  when: ansible_os_family == 'Debian'

# Suse
- name: Install mapr-core
  zypper: name={{ item }} state=present
  with_items:
  - mapr-compat-suse
  - mapr-core
  - mapr-core-internal
  when: ansible_os_family == 'Suse'
