---
- name: Copy keys to local
  fetch: src=/opt/mapr/conf/{{ item }} dest=/tmp/{{ item }} flat=yes
  with_items:
  - ssl_truststore
  - mapruserticket
  when: inventory_hostname == groups["mapr-cldb"][0]
- name: Copy Jars to local, required for Hive Server and Spark
  fetch: src=/opt/mapr/hadoop/hadoop-{{ hadoop_version }}/share/hadoop/yarn/{{ item }} dest=/tmp/{{ item }} flat=yes
  with_items:
  - hadoop-yarn-server-web-proxy-{{ hadoop_version }}-{{ mapr_build }}.jar
  - hadoop-yarn-server-common-{{ hadoop_version }}-{{ mapr_build }}.jar
  - hadoop-yarn-server-resourcemanager-{{ hadoop_version }}-{{ mapr_build }}.jar
  when: inventory_hostname == groups["mapr-cldb"][0]
