---
# Install mapr-posix-client-basic
# Redhat / CentOS
- name: Install mapr-posix-client-basic (Redhat / CentOS)
  yum: name={{ item }} state=present
  with_items:
  - mapr-posix-client-basic
  - rpcbind
  when: ansible_os_family == 'RedHat'
# Debian / Ubuntu
- name: Install mapr-nfs (Debian / Ubuntu)
  apt: name={{ item }} state=present allow_unauthenticated=yes
  with_items:
  - mapr-posix-client-basic
  - rpcbind
  when: ansible_os_family == 'Debian'
# Other
- name: Install mapr-posix-client-basic (Suse)
  zypper: name={{ item }} state=present
  with_items:
  - mapr-posix-client-basic
  - rpcbind
  when: ansible_os_family == 'Suse'

# Other actions
- name: Create /mapr dir
  file: path=/mapr state=directory
- name: Start the mapr-posix-client-basic service
  service: name=mapr-posix-client-basic state=started enabled=yes