---
# Download, Compile and Install Zeppelin
- name: Downloading NodeJS Setup
  get_url: url=https://rpm.nodesource.com/setup force=yes mode=0755 dest=/tmp/nodejs_setup timeout=120
- name:
  shell: /tmp/nodejs_setup
- name: Install build dependencies
  yum: name={{ item }} state=present
  with_items:
  - git
  - nodejs
#  - npm
#  - libfontconfig
  when: ansible_os_family == 'RedHat'
- name: Download and extract Maven 3.3.3
  unarchive: src=http://www.eu.apache.org/dist/maven/maven-3/3.3.3/binaries/apache-maven-3.3.3-bin.tar.gz dest=/usr/local/ copy=no
- name: Create mvn link
  file: src=/usr/local/apache-maven-3.3.3/bin/mvn dest=/usr/local/bin/mvn state=link
- name: Clone Zeppelin Git Repo
  git: repo=https://github.com/apache/incubator-zeppelin.git dest=/tmp/zeppelin.git
- name: Build Zeppelin with Maven
  shell: /usr/local/bin/mvn -Pmapr51 -Pyarn -Pbuild-distr -Pspark-1.6 -Phadoop-2.6 -Ppyspark package -DskipTests -B -f /tmp/zeppelin.git/pom.xml
- name: Create /opt/mapr/zeppelin dir
  file: path=/opt/mapr/zeppelin state=directory
- name: Create /opt/mapr/zeppelin/notebooks dir
  file: path=/opt/mapr/zeppelin/notebooks state=directory
#- name: Copy Zeppelin to /opt/mapr/zeppelin
#  unarchive: src=/tmp/zeppelin.git/zeppelin-distribution/target/zeppelin-{{ zeppelin_version }}.tar.gz dest=/opt/mapr/zeppelin/ copy=no
- name: Copy Zeppelin to /opt/mapr/zeppelin
  shell: cp -R /tmp/zeppelin.git/zeppelin-distribution/target/zeppelin-{{ zeppelin_version }}/zeppelin-{{ zeppelin_version }}/ /opt/mapr/zeppelin/
- name: Configure zeppelin-env.sh
  template: src=zeppelin-env.unsecure.sh dest=/opt/mapr/zeppelin/zeppelin-{{ zeppelin_version }}/conf/zeppelin-env.sh
- name: Configure zeppelin-site.xml
  template: src=zeppelin-site.unsecure.xml dest=/opt/mapr/zeppelin/zeppelin-{{ zeppelin_version }}/conf/zeppelin-site.xml
- name: Set owner mapr-system user
  file: path=/opt/mapr/zeppelin owner={{ mapr_user }} group={{ mapr_group }} state=directory recurse=yes
- name: Start Zeppelin
  shell: /opt/mapr/zeppelin/zeppelin-{{ zeppelin_version }}/bin/zeppelin-daemon.sh start

# copy zeppelin-env.sh

# copy drill driver

# start


# git clone https://github.com/apache/incubator-zeppelin.git





# Example read-write git checkout from github
#- git: repo=ssh://git@github.com/mylogin/hello.git dest=/home/mylogin/hello