---
# Install Hive CLI
- name: Install mysql-server
  yum: name=mariadb-server state=present
  when: ansible_os_family == 'RedHat'
- name: Start the mysqld service
  service: name=mariadb state=started enabled=yes
- name: Install python-mysql
  yum: name=MySQL-python state=present
  when: ansible_os_family == 'RedHat'
- name: Install mapr-hive
  yum: name=mapr-hive state=present
  when: ansible_os_family == 'RedHat'
- name: Create hive mysql db
  mysql_db: name={{ hive_db_schema }} state=present
- name: Create hive mysql user
  mysql_user: name={{ hive_db_user }} password={{ hive_db_password }} priv=hive.*:ALL state=present
- name: Downloading MySQL Driver
  unarchive: src={{ mysql_jdbc_url }} dest=/tmp copy=no
- name: Copy mysql driver
  copy: remote_src=True src=/tmp/mysql-connector-java-{{ mysql_jdbc_version }}/mysql-connector-java-{{ mysql_jdbc_version }}-bin.jar dest=/opt/mapr/hive/hive-{{ hive_version }}/lib/

- name: Get Thrift server
  set_fact: metastore_item=thrift://{{ hostvars[item]['ansible_fqdn'] }}:9093
  with_items:
    - "{{ groups['mapr-hive-metastore'] }}"
  register: metastore_hosts
- name: Make Resource Manager String
  set_fact: metastore_string={{ metastore_hosts.results | map(attribute='ansible_facts.metastore_item') | list | join(',')}}
- name: Configure hive-site.xml
  template: src=hive-site.unsecure.xml dest=/opt/mapr/hive/hive-{{ hive_version }}/conf/hive-site.xml
- name: Configure hive-env.sh
  template: src=hive-env.unsecure.sh dest=/opt/mapr/hive/hive-{{ hive_version }}/conf/hive-env.sh
- name: Add HIVE_HOME to /etc/profile
  lineinfile: dest=/etc/profile state=present line="export HIVE_HOME=/opt/mapr/hive/hive-{{ hive_version }}/"
- name: Set owner mapr-system user
  file: path=/opt/mapr/hive owner={{ mapr_user }} group={{ mapr_group }} state=directory recurse=yes