---
# Oracle JDK playbook
- name: Downloading Java JDK
  get_url: url={{ oracle_jdk_url }} force=yes mode=0440 headers="Cookie:oraclelicense=accept-securebackup-cookie" dest=/tmp/oracle-jdk.rpm timeout=120

#- name: Downloading Java JDK
#  shell:  curl -v -j -k -L -H "Cookie:oraclelicense=accept-securebackup-cookie" http://download.oracle.com/otn-pub/java/jdk/8u92-b14/jdk-8u92-linux-x64.rpm > /tmp/jdk-8u92-linux-x64.rpm

- name: Install Java JDK rpm from a local file
  yum: name=/tmp/oracle-jdk.rpm state=present

- name: Copy Local Policy
  copy: src="../files/UnlimitedJCEPolicyJDK8/local_policy.jar" dest="{{ oracle_jdk_folder }}/jre/lib/security/" mode=0644
- name: Copy US Export Policy
  copy: src="../files/UnlimitedJCEPolicyJDK8/US_export_policy.jar" dest="{{ oracle_jdk_folder }}/jre/lib/security/" mode=0644
- name: Add JAVA_HOME to /etc/profile
  lineinfile: dest=/etc/profile state=present line="export JAVA_HOME={{ oracle_jdk_folder }}"


#  - name: Copy /etc/environment with java and path settings
#    copy: src="../files/environment" dest="/etc/environment"
