---
# Install Oozie and MySQL
- name: Install mysql-server
  yum: name=mariadb-server state=present
  when: ansible_os_family == 'RedHat'
- name: Start the mysqld service
  service: name=mariadb state=started enabled=yes
- name: Install python-mysql
  yum: name=MySQL-python state=present
  when: ansible_os_family == 'RedHat'
- name: Install mapr-oozie
  yum: name=mapr-oozie state=present
  when: ansible_os_family == 'RedHat'
- name: Create oozie mysql db
  mysql_db: name={{ oozie_db_schema }} state=present
- name: Create oozie mysql user
  mysql_user: name={{ oozie_db_user }} password={{ oozie_db_password }} priv=oozie.*:ALL state=present
- name: Downloading MySQL Driver
  unarchive: src={{ mysql_jdbc_url }} dest=/tmp copy=no
- name: Copy mysql driver
  copy: remote_src=True src=/tmp/mysql-connector-java-{{ mysql_jdbc_version }}/mysql-connector-java-{{ mysql_jdbc_version }}-bin.jar dest=/opt/mapr/oozie/oozie-{{ oozie_version }}/libext/
- name: Configure oozie-site.xml
  template: src=oozie-site.unsecure.xml dest=/opt/mapr/oozie/oozie-{{ oozie_version }}/conf/oozie-site.xml
- name: Run oozie-setup.sh
  command: /opt/mapr/oozie/oozie-{{ oozie_version }}/bin/oozie-setup.sh -hadoop {{ hadoop_version }} /opt/mapr/hadoop/hadoop-{{ hadoop_version }}



