---
# Install Oozie and MySQL
# Redhat / CentOS
- name: Install MySQL (Redhat / CentOS)
  yum: name={{ item }} state=present
  with_items:
  - mariadb-server
  - MySQL-python
  when: ansible_os_family == 'RedHat'
- name: Start the mysqld service (Redhat / CentOS)
  service: name=mariadb state=started enabled=yes
  when: ansible_os_family == 'RedHat'
- name: Install mapr-oozie (Redhat / CentOS)
  yum: name=mapr-oozie state=present
  when: ansible_os_family == 'RedHat'
# Debian / Ubuntu
- name: Install MySQL (Debian / Ubuntu)
  apt: name={{ item }} state=present
  with_items:
  - mysql-server
  - mysql-client
  - python-mysqldb
  when: ansible_os_family == 'Debian'
- name: Start the mysqld service (Debian / Ubuntu)
  service: name=mysql state=started enabled=yes
  when: ansible_os_family == 'Debian'
- name: Install mapr-oozie (Debian / Ubuntu)
  apt: name=mapr-oozie state=present allow_unauthenticated=yes
  when: ansible_os_family == 'Debian'
# Suse
- name: Install MySQL (Suse)
  zypper: name={{ item }} state=present
  with_items:
  - mariadb
  - mariadb-client
  - python-mysql
  when: ansible_os_family == 'Suse'
- name: Start the mysqld service (Suse)
  service: name=mysql state=started enabled=yes
  when: ansible_os_family == 'Suse'
- name: Install mapr-oozie (Suse)
  zypper: name=mapr-oozie state=present
  when: ansible_os_family == 'Suse'

# Other
- name: Create oozie mysql db
  mysql_db: name={{ oozie_db_schema }} state=present
- name: Create oozie mysql user
  mysql_user: name={{ oozie_db_user }} password={{ oozie_db_password }} priv=oozie.*:ALL state=present
- name: Downloading MySQL Driver
  unarchive: src={{ mysql_jdbc_url }} dest=/tmp copy=no
- name: Copy mysql driver
  copy: remote_src=True src=/tmp/mysql-connector-java-{{ mysql_jdbc_version }}/mysql-connector-java-{{ mysql_jdbc_version }}-bin.jar dest=/opt/mapr/oozie/oozie-{{ oozie_version }}/libext/
- name: Configure oozie-site.xml
  template: src=oozie-site.unsecure.xml dest=/opt/mapr/oozie/oozie-{{ oozie_version }}/conf/oozie-site.xml
- name: Run oozie-setup.sh
  command: /opt/mapr/oozie/oozie-{{ oozie_version }}/bin/oozie-setup.sh -hadoop {{ hadoop_version }} /opt/mapr/hadoop/hadoop-{{ hadoop_version }}
- name: Set owner mapr-system user
  file: path=/opt/mapr/oozie owner={{ mapr_user }} group={{ mapr_group }} state=directory recurse=yes


