---
# Install MySQL
- name: Install mysql-server
  yum: name=mysql-server state=present
  when: ansible_os_family == 'RedHat'
- name: Start the mysqld service
  service: name=mysqld state=started enabled=yes