---
# Install MapR Client

# Redhat / CentOS
- name: Install mapr-core (Redhat / CentOS)
  yum: name=mapr-client state=present
  when: ansible_os_family == 'RedHat'
# Debian / Ubuntu
- name: Install mapr-core (Debian / Ubuntu)
  apt: name=mapr-client state=present allow_unauthenticated=yes
  when: ansible_os_family == 'Debian'
# Suse
- name: Install mapr-core (Suse)
  zypper: name=mapr-client state=present
  when: ansible_os_family == 'Suse'

# TODO
## Required for Spark
#- name: YARN proxy Jar
#  copy: src=/opt/mapr/hadoop/hadoop-2.7.0/share/hadoop/yarn/hadoop-yarn-server-web-proxy-2.7.0-mapr-1607.jar dest=/opt/mapr/hadoop/hadoop-2.7.0/share/hadoop/yarn/
# Required for Hive server
#- name: YARN RM Jar
#  copy: src=/opt/mapr/hadoop/hadoop-2.7.0/share/hadoop/yarn/hadoop-yarn-server-common-2.7.0-mapr-1607.jar dest=/opt/mapr/hadoop/hadoop-2.7.0/share/hadoop/yarn/
#- name: YARN RM Jar
#  copy: src=/opt/mapr/hadoop/hadoop-2.7.0/share/hadoop/yarn/hadoop-yarn-server-resourcemanager-2.7.0-mapr-1607.jar dest=/opt/mapr/hadoop/hadoop-2.7.0/share/hadoop/yarn/