---
# Restart Zookeeper and Warden
- name: Restart Zookeeper
  service: name=mapr-zookeeper state=restarted enabled=yes
- name: Restart MapR Warden
  service: name=mapr-warden state=restarted enabled=yes

