---
# Redhat / CentOS
# Install HBase REST
- name: Install mapr-hbase-rest (Redhat / CentOS)
  yum: name=mapr-hbase-rest state=present
  when: ansible_os_family == 'RedHat'
# Install HBase Thrift
- name: Install mapr-hbasethrift (Redhat / CentOS)
  yum: name=mapr-hbasethrift state=present
  when: ansible_os_family == 'RedHat'
# Debian / Ubuntu
# Install HBase REST
- name: Install mapr-hbase-rest (Debian / Ubuntu)
  apt: name=mapr-hbase-rest state=present
  when: ansible_os_family == 'Debian'
# Install HBase Thrift
- name: Install mapr-hbasethrift (Debian / Ubuntu)
  apt: name=mapr-hbasethrift state=present
  when: ansible_os_family == 'Debian'
# Suse
# Install HBase REST
- name: Install mapr-hbase-rest (Suse)
  zypper: name=mapr-hbase-rest state=present
  when: ansible_os_family == 'Suse'
# Install HBase Thrift
- name: Install mapr-hbasethrift (Suse)
  zypper: name=mapr-hbasethrift state=present
  when: ansible_os_family == 'Suse'